import React from "react";

export const metadata = {
  title: {
    default: "Auth | with layout",
    template: "%s | with layout",
  },
  description: "Generated by create next app",
};
function AuthLayout({ children }) {
  return <div>{children}</div>;
}

export default AuthLayout;
